export const FETCH_VEHICLES  = 'FECTH_VEHICLES';

export const FILTER_VEHICLES='FILTER_VEHICLES';
export const LOADING ='LOADING';
// export const FILTER_VEHICLES_BY_BODY_STYLE = 'FILTER_VEHICLES_BY_BODY_STYLE';
// export const FILTER_VEHICLES_BY_MIN_PRICE ='FILTER_VEHCILES_BY_MIN_PRICE';
// export const FILTER_VEHICLES_BY_MAX_PRICE ='FILTER_VEHCILES_BY_MAX_PRICE';
export const ADD_TO_CART ='ADD_TO_CART';
export const REMOVE_FROM_CART ='REMOVE_FROM_CART';
export const ITEM_IN_CART = 'ITEM_IN_CART';
export const ERROR = 'ERROR';